package exception;

public class Arithmetic {

	public static void main(String[] args) {
		try {
			
			String name="swati";
			
			int a=10;
			int b=0;
			 int c= a/b;
	
			 System.out.print( c);
			
		} catch (Exception e) {
			System.out.println("catch block");
		}

	}

}
